fluidPage(#theme = shinytheme("united"),

HTML("<div style='background-color:rgba(63, 174, 191, 0.0); text-align:center; vertical-align: middle; padding:40px 0;'><h1><b> Animal Observer data editor </b></h1></div>"),

##h1("Animal Observer data editor"),
    wellPanel(
    fluidRow(
    column(3,
     h5('1. Upload "Username_Date_Time.dat"'),
     fileInput('json.output.file', label=NULL),
    HTML('<hr style="height:1px;border:none;color:#333;background-color:#333;" />'),
    h5('2. Upload "behaviors.json"'),
	fileInput('behaviors.json', label=NULL),
    HTML('<hr style="height:1px;border:none;color:#333;background-color:#333;" />'),
    h5('3. Upload "layout_info.json"'),
    fileInput('layout_info.json', label=NULL)
    ),
    column(5,
    h5("4. Ready to edit (can take a few seconds)?"),
   
    checkboxInput("colmerge", "Merge identically-named columns from dyadic and self-directed/health data", TRUE),
    actionButton("VisualizeData", label = "Run", icon=icon("play")),
	HTML('<hr style="height:1px;border:none;color:#333;background-color:#333;" />'),
    
    h5("5. Edit using tables below and download results here"),
    downloadButton("downloadZip", label = "Download all data as zip"),
     br(), h5("    OR"),      
      downloadButton('downloadSessionsTable', 'Download list of sessions'),
      downloadButton('downloadFocalsTable', 'Download list of focals'),
      downloadButton('downloadBehaviorsTable', 'Download list of behaviors'),
	  downloadButton('downloadScansTable', 'Download list of scans'),
	  downloadButton('downloadBackgroundTapsTable', 'Download list of background taps'),
	  downloadButton('downloadCommentsTable', 'Download list of comments'),
	  downloadButton('downloadDayVarsTable', 'Download day variables'),
	  downloadButton('downloadFocalVarsTable', 'Download focal variables'),
	  downloadButton('downloadContinuousVarsTable', 'Download global variables'),
  	  downloadButton('downloadScanVarsTable', 'Download scan variables')
  	  ),
  	column(3,
    h5("6. PostgreSQL database connection"),
   
    textInput("postgresHost", label = "Host name or IP address", value = "localhost"),
    textInput("postgresDBname", label = "Database name", value = "postgres"),
	textInput("postgresUser", label = "User name", value = "postgres"),
	numericInput("postgresPort", label = "Port", value = "5432"),
	passwordInput("postgresPwd", label = "Password (non-encrypted, use a VPN for safer connection!)", value = "postgres"),
	actionButton("postgresConnect", label = "Connect"),
	textOutput("DoneConnect"),	
	HTML('<hr style="height:1px;border:none;color:#333;background-color:#333;" />'),
	h5("7. Upload Zip folder to database"),
	fileInput('zipFolder', '', accept=),
	actionButton("runZipUpload", label = "Upload"),	textOutput("DoneUploading")
  	  )
  )), 
    
    #fluidRow(column(3, verbatimTextOutput("value"))),
      br(),
  	# downloadButton("downloadBehaviorsView", "Download behaviors", icon=icon('download'), style="color: #090909; background-color: #cdcdcd; border-color: #090909"),
  	# downloadButton("downloadScansView", "Download scans", icon=icon('download'), style="color: #090909; background-color: #cdcdcd; border-color: #090909"),
  	selectInput('sessionSelect', label = "Select a session", choices = list("ALL" = 1), selected = 1, width="50%"),
  	HTML("<div style='background-color:rgba(63, 174, 191, 0.60); text-align:center; vertical-align: middle; padding:3px 0;'><h3> Sessions </h3></div>"),
  
  	br(),
    d3tfOutput('sessionsDT', height = "auto"),
	br(),
	actionButton('duplicateSessionRow', 'Duplicate selected row', icon=icon('copy'), style="color: #090909; background-color: #cdcdcd; border-color: #090909"),
	#actionButton('addBlankSessionRow', 'Add blank row', icon=icon('plus'), style="color: #090909; background-color: #cdcdcd; border-color: #090909"),
	actionButton('deleteSessionRow', 'Delete selected row', icon=icon('close'), style="color: #090909; background-color: #cdcdcd; border-color: #090909"),
    hr(),
    hr(),
    HTML("<div style='background-color:rgba(63, 174, 191, 0.30); text-align:center; vertical-align: middle; padding:1px 0;'><h4> Session variables </h4></div>"),
    ###HTML("<h4><b>    Session variables</b></h3>"),
	br(),
    d3tfOutput('dayVarsDT', height = "auto"),
	br(),
	actionButton('duplicateDayVarsRow', 'Duplicate selected row', icon=icon('copy'), style="color: #090909; background-color: #cdcdcd; border-color: #090909"),
	#actionButton('addBlankSessionRow', 'Add blank row', icon=icon('plus'), style="color: #090909; background-color: #cdcdcd; border-color: #090909"),
	actionButton('deleteDayVarsRow', 'Delete selected row', icon=icon('close'), style="color: #090909; background-color: #cdcdcd; border-color: #090909"),
    br(),
    	HTML('<hr style="height:2px;border:none;color:#333;background-color:#333;" />'),
    	br(),
    HTML("<div style='background-color:rgba(104, 191, 63, 0.60); text-align:center; vertical-align: middle; padding:3px 0;'><h3> Focal samples </h3></div>"),
   ## HTML("<h3><b>    Focal samples</b></h3>"),
	br(),
    d3tfOutput('focalsDT', height = "auto"),
	br(),
	actionButton('duplicateFocalRow', 'Duplicate selected row', icon=icon('copy'), style="color: #090909; background-color: #cdcdcd; border-color: #090909"),
	#actionButton('addBlankSessionRow', 'Add blank row', icon=icon('plus'), style="color: #090909; background-color: #cdcdcd; border-color: #090909"),
	actionButton('deleteFocalRow', 'Delete selected row', icon=icon('close'), style="color: #090909; background-color: #cdcdcd; border-color: #090909"),
    hr(),
    hr(),
    HTML("<div style='background-color:rgba(104, 191, 63, 0.30); text-align:center; vertical-align: middle; padding:1px 0;'><h4> Background taps </h4></div>"),
    ##HTML("<h4><b>    Background taps</b></h3>"),
	br(),
    d3tfOutput('backgroundTapsDT', height = "auto"),
	br(),
	actionButton('duplicateBackgroundTapsRow', 'Duplicate selected row', icon=icon('copy'), style="color: #090909; background-color: #cdcdcd; border-color: #090909"),
	#actionButton('addBlankSessionRow', 'Add blank row', icon=icon('plus'), style="color: #090909; background-color: #cdcdcd; border-color: #090909"),
	actionButton('deleteBackgroundTapsRow', 'Delete selected row', icon=icon('close'), style="color: #090909; background-color: #cdcdcd; border-color: #090909"),
    hr(),
    hr(),
	HTML("<div style='background-color:rgba(104, 191, 63, 0.30); text-align:center; vertical-align: middle; padding:1px 0;'><h4> Dyadic and self-directed/health data </h4></div>"),
    ##HTML("<h3><b>    Dyadic and self-directed/health data</b></h3>"),
    br(),    
    d3tfOutput('behaviorsDT', height = "auto"),
	br(),  
	actionButton('duplicateBehaviorRow', 'Duplicate selected row', icon=icon('copy'), style="color: #090909; background-color: #cdcdcd; border-color: #090909"),
	#actionButton('addBlankSessionRow', 'Add blank row', icon=icon('plus'), style="color: #090909; background-color: #cdcdcd; border-color: #090909"),
	actionButton('deleteBehaviorRow', 'Delete selected row', icon=icon('close'), style="color: #090909; background-color: #cdcdcd; border-color: #090909"),  
    hr(),
    hr(),
    HTML("<div style='background-color:rgba(104, 191, 63, 0.30); text-align:center; vertical-align: middle; padding:1px 0;'><h4> Focal variables </h4></div>"),
    ##HTML("<h4><b>    Focal variables</b></h3>"),
	br(),
    d3tfOutput('focalVarsDT', height = "auto"),
	br(),
	actionButton('duplicateFocalVarsRow', 'Duplicate selected row', icon=icon('copy'), style="color: #090909; background-color: #cdcdcd; border-color: #090909"),
	#actionButton('addBlankSessionRow', 'Add blank row', icon=icon('plus'), style="color: #090909; background-color: #cdcdcd; border-color: #090909"),
	actionButton('deleteFocalVarsRow', 'Delete selected row', icon=icon('close'), style="color: #090909; background-color: #cdcdcd; border-color: #090909"),
    hr(),
    hr(),
    HTML("<div style='background-color:rgba(104, 191, 63, 0.30); text-align:center; vertical-align: middle; padding:1px 0;'><h4> Continuous variables variables </h4></div>"),
   ##HTML("<h4><b>    Continuous variables variables</b></h3>"),
	br(),
    d3tfOutput('continuousVarsDT', height = "auto"),
	br(),
	actionButton('duplicateContinuousVarsRow', 'Duplicate selected row', icon=icon('copy'), style="color: #090909; background-color: #cdcdcd; border-color: #090909"),
	#actionButton('addBlankSessionRow', 'Add blank row', icon=icon('plus'), style="color: #090909; background-color: #cdcdcd; border-color: #090909"),
	actionButton('deleteContinuousVarsRow', 'Delete selected row', icon=icon('close'), style="color: #090909; background-color: #cdcdcd; border-color: #090909"),
    hr(),
    hr(),
    HTML("<div style='background-color:rgba(104, 191, 63, 0.30); text-align:center; vertical-align: middle; padding:1px 0;'><h4> Focal comments </h4></div>"),
    ##HTML("<h4><b>    Focal comments</b></h3>"),
	br(),
    d3tfOutput('commentsDT', height = "auto"),
	br(),
	actionButton('duplicateCommentsRow', 'Duplicate selected row', icon=icon('copy'), style="color: #090909; background-color: #cdcdcd; border-color: #090909"),
	#actionButton('addBlankSessionRow', 'Add blank row', icon=icon('plus'), style="color: #090909; background-color: #cdcdcd; border-color: #090909"),
	actionButton('deleteCommentsRow', 'Delete selected row', icon=icon('close'), style="color: #090909; background-color: #cdcdcd; border-color: #090909"),
	br(),
    HTML('<hr style="height:2px;border:none;color:#333;background-color:#333;" />'),
    br(),
    HTML("<div style='background-color:rgba(237, 158, 22, 0.60); text-align:center; vertical-align: middle; padding:3px 0;'><h3> Scan samples </h3></div>"),
    ##HTML("<h3><b>    Scans list</b></h3>"),
	br(),    
    d3tfOutput('scanListDT', height = "auto"),
    br(),
    actionButton('duplicateScanListRow', 'Duplicate selected row', icon=icon('copy'), style="color: #090909; background-color: #cdcdcd; border-color: #090909"),
	#actionButton('addBlankSessionRow', 'Add blank row', icon=icon('plus'), style="color: #090909; background-color: #cdcdcd; border-color: #090909"),
	actionButton('deleteScanListRow', 'Delete selected row', icon=icon('close'), style="color: #090909; background-color: #cdcdcd; border-color: #090909"),
    hr(),
    hr(),
    HTML("<div style='background-color:rgba(237, 158, 22, 0.30); text-align:center; vertical-align: middle; padding:1px 0;'><h4> Scan data </h4></div>"),
    ##HTML("<h3><b>    Scan data</b></h3>"),
	br(), 
    d3tfOutput('scansDT', height = "auto"),
    br(),
    actionButton('duplicateScanRow', 'Duplicate selected row', icon=icon('copy'), style="color: #090909; background-color: #cdcdcd; border-color: #090909"),
	#actionButton('addBlankSessionRow', 'Add blank row', icon=icon('plus'), style="color: #090909; background-color: #cdcdcd; border-color: #090909"),
	actionButton('deleteScanRow', 'Delete selected row', icon=icon('close'), style="color: #090909; background-color: #cdcdcd; border-color: #090909"),    
    hr(),
    hr(),
    HTML("<div style='background-color:rgba(237, 158, 22, 0.30); text-align:center; vertical-align: middle; padding:1px 0;'><h4> Scan variables </h4></div>"),
    ##HTML("<h4><b>    Scan variables</b></h3>"),
	br(),
    d3tfOutput('scanVarsDT', height = "auto"),
	br(),
	actionButton('duplicateScanVarsRow', 'Duplicate selected row', icon=icon('copy'), style="color: #090909; background-color: #cdcdcd; border-color: #090909"),
	#actionButton('addBlankSessionRow', 'Add blank row', icon=icon('plus'), style="color: #090909; background-color: #cdcdcd; border-color: #090909"),
	actionButton('deleteScanVarsRow', 'Delete selected row', icon=icon('close'), style="color: #090909; background-color: #cdcdcd; border-color: #090909"),
    br(),
    HTML('<hr style="height:2px;border:none;color:#333;background-color:#333;" />'),
    br()
)


